version: '3'
services:
  backend:
    build: .
    mem_limit: 800m
    ports:
      - "8000:8000"
  envoy:
    image: "envoyproxy/envoy-alpine"
    network_mode: host
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - "./etc/envoy.yaml:/etc/envoy.yaml"
      - "./var/log/envoy:/var/log/envoy"
    command: ["envoy", "-c", "/etc/envoy.yaml"]