version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 800M
        reservations:
          cpus: '0.70'
          memory: 500M
  envoy:
    image: "envoyproxy/envoy-alpine"
    network_mode: host
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - "./etc/envoy.yaml:/etc/envoy.yaml"
      - "./var/log/envoy:/var/log/envoy"
    command: ["envoy", "-c", "/etc/envoy.yaml"]